### ISSUE TITLE
Incorrect SPI wiring to Gyro ICM

### ISSUE THREAD

**Issue by sherpavel** [tropicalfpv/thunderFC#1]
# Issue description
I built a flight controller from your PCB design, but BetaFlight firmware was unable to find the gyro module. After reviewing your design, I found that SPI data pins on ICM-20689 are wired incorrectly to STM32, in particular SDO (pin 9) and SDI (pin 24). 
On a SPI peripheral SDO corresponds to MISO and SDI - to MOSI. After re-wiring data pins manually, the gyro became operational.

# How to solve
Connect data pins as following:
ICM SDO (9) --> SPI1_MISO (PA6 / 22)
ICM SDI (24) <-- SPI1_MOSI (PA7 / 23)

![image](https://github.com/user-attachments/assets/18d65c1f-d92b-4780-a122-8747d624207b)

**Comment by anardine** [comment]
Thanks @sherpavel for this. I've just rewired it and it's now correct.

Did you stress the FC out? How was the flight? If you can, please add some black-box logging as a commit in a new file. I'll be doing the same, but since manufacturing and shipping to Brazil take ages, it's a long wait before I can even get one.

I'm happy to have you as the first to try this out!
